apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
spec:
  type: NodePort
  selector:
    app: scaletestapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007